### ISSUE TITLE
Issue-started database -- parametri

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#12]
Automated Review Comments
Issues in coin-collector/package-lock.json:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in coin-collector/package.json:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in coin-collector/src/app/database/indexed-db.class.ts:
  - (2, 'Hardcoded string found')
Issues in coin-collector/src/app/database/indexed-db.service.spec.ts:
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in coin-collector/src/app/database/indexed-db.service.ts:
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (112, 'Line exceeds 80 characters')
  - (112, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (115, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (130, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
Issues in coin-collector/src/app/database/population.data.ts:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
