### ISSUE TITLE
Issue-parametri component done

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#14]
Automated Review Comments
Issues in coin-collector/src/app/app-routing.module.ts:
  - (10, 'Hardcoded string found')
Issues in coin-collector/src/app/app.module.ts:
  - (1, 'Line exceeds 80 characters')
Issues in coin-collector/src/app/parametri/parametri.component.html:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
Issues in coin-collector/src/app/parametri/parametri.component.spec.ts:
  - (6, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in coin-collector/src/app/parametri/parametri.component.ts:
  - (5, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')

**Comment by williamddobson3** [comment]
I got it.
