### ISSUE TITLE
Issue-units -- added component -- added to db with ambito

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#16]
Automated Review Comments
Issues in coin-collector/src/app/app-routing.module.ts:
  - (10, 'Hardcoded string found')
Issues in coin-collector/src/app/app.module.ts:
  - (1, 'Line exceeds 80 characters')
Issues in coin-collector/src/app/database/indexed-db.class.ts:
  - (2, 'Hardcoded string found')
Issues in coin-collector/src/app/database/indexed-db.service.ts:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
Issues in coin-collector/src/app/database/population.data.ts:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
Issues in coin-collector/src/app/interface/interface.service.ts:
  - (1, 'Hardcoded string found')
Issues in coin-collector/src/app/interface/menu.ts:
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
Issues in coin-collector/src/app/parametri/parametri.component.ts:
  - (3, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in coin-collector/src/app/units/units.component.html:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
Issues in coin-collector/src/app/units/units.component.spec.ts:
  - (6, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in coin-collector/src/app/units/units.component.ts:
  - (5, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')

**Comment by williamddobson3** [comment]
I got it.
