### ISSUE TITLE
Issue-added backup -- deploy in package.json -- fix units -- key shortcuts

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#24]
Automated Review Comments
Issues in coin-collector/electron/main.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in coin-collector/package-lock.json:
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (102, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Line exceeds 80 characters')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Line exceeds 80 characters')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (213, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Line exceeds 80 characters')
  - (222, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Line exceeds 80 characters')
  - (225, 'Hardcoded string found')
  - (226, 'Line exceeds 80 characters')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Line exceeds 80 characters')
  - (237, 'Hardcoded string found')
  - (238, 'Line exceeds 80 characters')
  - (238, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Line exceeds 80 characters')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (256, 'Line exceeds 80 characters')
  - (256, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (264, 'Hardcoded string found')
  - (265, 'Line exceeds 80 characters')
  - (265, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Line exceeds 80 characters')
  - (267, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (280, 'Line exceeds 80 characters')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Line exceeds 80 characters')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (298, 'Line exceeds 80 characters')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (300, 'Line exceeds 80 characters')
  - (300, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Line exceeds 80 characters')
  - (304, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (318, 'Line exceeds 80 characters')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (323, 'Line exceeds 80 characters')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Line exceeds 80 characters')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Line exceeds 80 characters')
  - (333, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (338, 'Line exceeds 80 characters')
  - (338, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (345, 'Line exceeds 80 characters')
  - (345, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Line exceeds 80 characters')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Line exceeds 80 characters')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Line exceeds 80 characters')
  - (371, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (375, 'Line exceeds 80 characters')
  - (375, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Line exceeds 80 characters')
  - (378, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (381, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (390, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Line exceeds 80 characters')
  - (395, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (405, 'Line exceeds 80 characters')
  - (405, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Line exceeds 80 characters')
  - (418, 'Hardcoded string found')
  - (419, 'Line exceeds 80 characters')
  - (419, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (432, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (440, 'Line exceeds 80 characters')
  - (440, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (444, 'Line exceeds 80 characters')
  - (444, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (448, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (451, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (456, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (460, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (467, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (471, 'Line exceeds 80 characters')
  - (471, 'Hardcoded string found')
  - (472, 'Line exceeds 80 characters')
  - (472, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Line exceeds 80 characters')
  - (479, 'Hardcoded string found')
  - (480, 'Line exceeds 80 characters')
  - (480, 'Hardcoded string found')
  - (481, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (489, 'Hardcoded string found')
Issues in coin-collector/package.json:
  - (2, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in coin-collector/src/app/app.component.ts:
  - (6, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
Issues in coin-collector/src/app/app.module.ts:
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
Issues in coin-collector/src/app/gestione/backup/backup-progress/backup-progress.component.html:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in coin-collector/src/app/gestione/backup/backup-progress/backup-progress.component.spec.ts:
  - (6, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in coin-collector/src/app/gestione/backup/backup-progress/backup-progress.component.ts:
  - (18, 'Line exceeds 80 characters')
Issues in coin-collector/src/app/gestione/backup/backup.component.html:
  - (5, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
Issues in coin-collector/src/app/gestione/backup/backup.component.ts:
  - (5, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
Issues in coin-collector/src/app/system/system.service.ts:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (447, 'Line exceeds 80 characters')
  - (475, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (481, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (487, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (493, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (502, 'Hardcoded string found')
  - (505, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (511, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (538, 'Hardcoded string found')
  - (541, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (547, 'Hardcoded string found')
  - (550, 'Hardcoded string found')
  - (553, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (559, 'Hardcoded string found')
  - (562, 'Hardcoded string found')
  - (565, 'Hardcoded string found')
  - (568, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (584, 'Hardcoded string found')
  - (589, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (596, 'Line exceeds 80 characters')
  - (599, 'Hardcoded string found')
  - (603, 'Hardcoded string found')
  - (610, 'Hardcoded string found')
  - (628, 'Hardcoded string found')
  - (646, 'Hardcoded string found')
  - (654, 'Hardcoded string found')
  - (655, 'Hardcoded string found')
  - (656, 'Hardcoded string found')
  - (658, 'Hardcoded string found')
  - (667, 'Hardcoded string found')
  - (671, 'Hardcoded string found')
  - (679, 'Line exceeds 80 characters')
  - (680, 'Line exceeds 80 characters')
  - (701, 'Line exceeds 80 characters')
Issues in coin-collector/src/app/units/units.component.html:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
