### ISSUE TITLE
Issue-changed version

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#26]
Automated Review Comments
Issues in coin-collector/electron/main.ts:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in coin-collector/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
