### ISSUE TITLE
Issue-added electron-packager in package.json

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#28]
Automated Review Comments
Issues in coin-collector/package-lock.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (98, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Line exceeds 80 characters')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
  - (127, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Line exceeds 80 characters')
  - (140, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Line exceeds 80 characters')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (193, 'Line exceeds 80 characters')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Line exceeds 80 characters')
  - (201, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Line exceeds 80 characters')
  - (208, 'Hardcoded string found')
  - (209, 'Line exceeds 80 characters')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Line exceeds 80 characters')
  - (227, 'Hardcoded string found')
  - (228, 'Line exceeds 80 characters')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Line exceeds 80 characters')
  - (239, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Line exceeds 80 characters')
  - (246, 'Hardcoded string found')
  - (247, 'Line exceeds 80 characters')
  - (247, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (260, 'Line exceeds 80 characters')
  - (260, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (268, 'Line exceeds 80 characters')
  - (268, 'Hardcoded string found')
  - (269, 'Line exceeds 80 characters')
  - (269, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Line exceeds 80 characters')
  - (293, 'Hardcoded string found')
  - (294, 'Line exceeds 80 characters')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (300, 'Line exceeds 80 characters')
  - (300, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (308, 'Line exceeds 80 characters')
  - (308, 'Hardcoded string found')
  - (309, 'Line exceeds 80 characters')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (320, 'Line exceeds 80 characters')
  - (320, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (325, 'Hardcoded string found')
  - (326, 'Line exceeds 80 characters')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (331, 'Line exceeds 80 characters')
  - (331, 'Hardcoded string found')
  - (332, 'Line exceeds 80 characters')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (336, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (343, 'Line exceeds 80 characters')
  - (343, 'Hardcoded string found')
  - (345, 'Line exceeds 80 characters')
  - (345, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Line exceeds 80 characters')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (352, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Line exceeds 80 characters')
  - (361, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Line exceeds 80 characters')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (377, 'Line exceeds 80 characters')
  - (377, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (381, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (390, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (403, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (432, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (440, 'Hardcoded string found')
  - (441, 'Hardcoded string found')
  - (442, 'Line exceeds 80 characters')
  - (442, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (448, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (451, 'Line exceeds 80 characters')
  - (451, 'Hardcoded string found')
  - (452, 'Hardcoded string found')
  - (456, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (460, 'Line exceeds 80 characters')
  - (460, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (465, 'Line exceeds 80 characters')
  - (465, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (467, 'Hardcoded string found')
  - (468, 'Hardcoded string found')
  - (469, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (476, 'Hardcoded string found')
  - (477, 'Line exceeds 80 characters')
  - (477, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (483, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (489, 'Line exceeds 80 characters')
  - (489, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (493, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (497, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Hardcoded string found')
  - (503, 'Hardcoded string found')
  - (504, 'Line exceeds 80 characters')
  - (504, 'Hardcoded string found')
  - (505, 'Hardcoded string found')
  - (506, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (514, 'Hardcoded string found')
  - (515, 'Line exceeds 80 characters')
  - (515, 'Hardcoded string found')
  - (516, 'Hardcoded string found')
  - (517, 'Hardcoded string found')
  - (518, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (525, 'Line exceeds 80 characters')
  - (525, 'Hardcoded string found')
  - (526, 'Hardcoded string found')
  - (527, 'Hardcoded string found')
  - (532, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (535, 'Line exceeds 80 characters')
  - (535, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (538, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (540, 'Hardcoded string found')
  - (541, 'Hardcoded string found')
  - (542, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (547, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (549, 'Line exceeds 80 characters')
  - (549, 'Hardcoded string found')
  - (551, 'Line exceeds 80 characters')
  - (551, 'Hardcoded string found')
  - (552, 'Hardcoded string found')
  - (555, 'Hardcoded string found')
  - (556, 'Line exceeds 80 characters')
  - (556, 'Hardcoded string found')
  - (557, 'Hardcoded string found')
  - (558, 'Hardcoded string found')
  - (561, 'Hardcoded string found')
  - (562, 'Line exceeds 80 characters')
  - (562, 'Hardcoded string found')
  - (564, 'Hardcoded string found')
  - (567, 'Hardcoded string found')
  - (568, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (570, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (573, 'Hardcoded string found')
  - (574, 'Hardcoded string found')
  - (575, 'Line exceeds 80 characters')
  - (575, 'Hardcoded string found')
  - (576, 'Hardcoded string found')
  - (577, 'Hardcoded string found')
  - (578, 'Hardcoded string found')
  - (581, 'Hardcoded string found')
  - (583, 'Hardcoded string found')
  - (585, 'Hardcoded string found')
  - (586, 'Line exceeds 80 characters')
  - (586, 'Hardcoded string found')
  - (587, 'Hardcoded string found')
  - (588, 'Hardcoded string found')
  - (589, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (592, 'Hardcoded string found')
  - (594, 'Hardcoded string found')
  - (597, 'Hardcoded string found')
  - (598, 'Hardcoded string found')
  - (599, 'Line exceeds 80 characters')
  - (599, 'Hardcoded string found')
  - (600, 'Hardcoded string found')
  - (601, 'Hardcoded string found')
  - (602, 'Hardcoded string found')
  - (608, 'Hardcoded string found')
  - (609, 'Hardcoded string found')
  - (610, 'Hardcoded string found')
  - (616, 'Hardcoded string found')
  - (617, 'Line exceeds 80 characters')
  - (617, 'Hardcoded string found')
  - (618, 'Hardcoded string found')
  - (619, 'Hardcoded string found')
  - (620, 'Hardcoded string found')
  - (625, 'Hardcoded string found')
  - (626, 'Line exceeds 80 characters')
  - (626, 'Hardcoded string found')
  - (631, 'Hardcoded string found')
  - (632, 'Hardcoded string found')
  - (633, 'Hardcoded string found')
  - (634, 'Line exceeds 80 characters')
  - (634, 'Hardcoded string found')
  - (635, 'Hardcoded string found')
  - (636, 'Hardcoded string found')
  - (638, 'Hardcoded string found')
  - (639, 'Hardcoded string found')
  - (642, 'Hardcoded string found')
  - (643, 'Hardcoded string found')
  - (644, 'Line exceeds 80 characters')
  - (644, 'Hardcoded string found')
  - (649, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (651, 'Hardcoded string found')
  - (652, 'Line exceeds 80 characters')
  - (652, 'Hardcoded string found')
  - (653, 'Hardcoded string found')
  - (656, 'Hardcoded string found')
  - (657, 'Line exceeds 80 characters')
  - (657, 'Hardcoded string found')
  - (659, 'Line exceeds 80 characters')
  - (659, 'Hardcoded string found')
  - (660, 'Line exceeds 80 characters')
  - (660, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
  - (664, 'Line exceeds 80 characters')
  - (664, 'Hardcoded string found')
  - (665, 'Hardcoded string found')
  - (666, 'Hardcoded string found')
  - (667, 'Hardcoded string found')
  - (672, 'Hardcoded string found')
  - (673, 'Line exceeds 80 characters')
  - (673, 'Hardcoded string found')
  - (678, 'Hardcoded string found')
  - (679, 'Hardcoded string found')
  - (680, 'Hardcoded string found')
  - (681, 'Hardcoded string found')
  - (682, 'Hardcoded string found')
  - (683, 'Hardcoded string found')
  - (684, 'Hardcoded string found')
  - (686, 'Hardcoded string found')
  - (687, 'Hardcoded string found')
  - (688, 'Hardcoded string found')
  - (689, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (691, 'Hardcoded string found')
  - (692, 'Hardcoded string found')
  - (693, 'Hardcoded string found')
  - (699, 'Hardcoded string found')
  - (700, 'Line exceeds 80 characters')
  - (700, 'Hardcoded string found')
  - (705, 'Hardcoded string found')
  - (706, 'Hardcoded string found')
  - (707, 'Hardcoded string found')
  - (708, 'Hardcoded string found')
  - (709, 'Hardcoded string found')
  - (712, 'Hardcoded string found')
  - (713, 'Hardcoded string found')
  - (715, 'Hardcoded string found')
  - (719, 'Hardcoded string found')
  - (720, 'Line exceeds 80 characters')
  - (720, 'Hardcoded string found')
  - (721, 'Hardcoded string found')
  - (722, 'Hardcoded string found')
  - (723, 'Hardcoded string found')
  - (728, 'Hardcoded string found')
  - (729, 'Hardcoded string found')
  - (731, 'Hardcoded string found')
  - (735, 'Hardcoded string found')
  - (736, 'Line exceeds 80 characters')
  - (736, 'Hardcoded string found')
  - (737, 'Hardcoded string found')
  - (738, 'Hardcoded string found')
  - (740, 'Hardcoded string found')
  - (741, 'Hardcoded string found')
  - (742, 'Hardcoded string found')
  - (744, 'Hardcoded string found')
  - (745, 'Hardcoded string found')
  - (747, 'Hardcoded string found')
  - (748, 'Hardcoded string found')
  - (749, 'Hardcoded string found')
  - (750, 'Hardcoded string found')
  - (751, 'Hardcoded string found')
  - (754, 'Hardcoded string found')
  - (755, 'Line exceeds 80 characters')
  - (755, 'Hardcoded string found')
Issues in coin-collector/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
