### ISSUE TITLE
Issue-added installer and icons

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#30]
Automated Review Comments
Issues in coin-collector/electron/main-window.ts:
  - (1, 'Hardcoded string found')
Issues in coin-collector/electron/main.ts:
  - (2, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
Issues in coin-collector/electron/splash-window.ts:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in coin-collector/electron/squirrel-event.ts:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in coin-collector/installer/build.ts:
  - (7, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
Issues in coin-collector/installer/tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in coin-collector/package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (115, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Line exceeds 80 characters')
  - (121, 'Hardcoded string found')
  - (122, 'Line exceeds 80 characters')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (241, 'Line exceeds 80 characters')
  - (241, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (245, 'Line exceeds 80 characters')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (250, 'Line exceeds 80 characters')
  - (250, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (257, 'Line exceeds 80 characters')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (266, 'Line exceeds 80 characters')
  - (266, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Line exceeds 80 characters')
  - (274, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Line exceeds 80 characters')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Line exceeds 80 characters')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (301, 'Line exceeds 80 characters')
  - (301, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (336, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (338, 'Line exceeds 80 characters')
  - (338, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
Issues in coin-collector/package.json:
  - (3, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
