### ISSUE TITLE
Issue-started angular project

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#4]
Automated Review Comments
Issues in coin-collector/README.md:
  - (4, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
Issues in coin-collector/angular.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
Issues in coin-collector/e2e/protractor.conf.js:
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
Issues in coin-collector/e2e/src/app.e2e-spec.ts:
  - (11, 'Hardcoded string found')
Issues in coin-collector/e2e/src/app.po.ts:
  - (2, 'Hardcoded string found')
Issues in coin-collector/e2e/tsconfig.e2e.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in coin-collector/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
Issues in coin-collector/src/app/app.component.html:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
Issues in coin-collector/src/app/app.component.spec.ts:
  - (6, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
Issues in coin-collector/src/browserslist:
  - (2, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
Issues in coin-collector/src/environments/environment.ts:
  - (2, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
Issues in coin-collector/src/index.html:
  - (3, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in coin-collector/src/karma.conf.js:
  - (8, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
Issues in coin-collector/src/polyfills.ts:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
Issues in coin-collector/src/test.ts:
  - (2, 'Line exceeds 80 characters')
Issues in coin-collector/src/tsconfig.app.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in coin-collector/src/tsconfig.spec.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in coin-collector/src/tslint.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
