### ISSUE TITLE
Issue-Create README.md

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#40]
Automated Review Comments
Issues in README.md:
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')

**Comment by williamddobson3** [comment]
I got it.
