### ISSUE TITLE
Issue-setted up electron project - package.json scripts - gitignore

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#6]
Automated Review Comments
Issues in coin-collector/angular.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in coin-collector/electron/main-window.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
Issues in coin-collector/electron/main.ts:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in coin-collector/electron/tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in coin-collector/package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (138, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Line exceeds 80 characters')
  - (154, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (172, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (198, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Line exceeds 80 characters')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (244, 'Line exceeds 80 characters')
  - (244, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (252, 'Line exceeds 80 characters')
  - (252, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (259, 'Line exceeds 80 characters')
  - (259, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
  - (264, 'Hardcoded string found')
  - (265, 'Line exceeds 80 characters')
  - (265, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Line exceeds 80 characters')
  - (278, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Line exceeds 80 characters')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (297, 'Line exceeds 80 characters')
  - (297, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Line exceeds 80 characters')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (318, 'Line exceeds 80 characters')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (330, 'Line exceeds 80 characters')
  - (330, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (336, 'Line exceeds 80 characters')
  - (336, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (338, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (365, 'Line exceeds 80 characters')
  - (365, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (373, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (376, 'Line exceeds 80 characters')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (384, 'Line exceeds 80 characters')
  - (384, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (390, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (399, 'Line exceeds 80 characters')
  - (399, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (415, 'Line exceeds 80 characters')
  - (415, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Line exceeds 80 characters')
  - (421, 'Hardcoded string found')
  - (423, 'Line exceeds 80 characters')
  - (423, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (426, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (432, 'Hardcoded string found')
  - (433, 'Line exceeds 80 characters')
  - (433, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Line exceeds 80 characters')
  - (439, 'Hardcoded string found')
  - (441, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (446, 'Line exceeds 80 characters')
  - (446, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (448, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (455, 'Line exceeds 80 characters')
  - (455, 'Hardcoded string found')
  - (460, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (462, 'Line exceeds 80 characters')
  - (462, 'Hardcoded string found')
  - (463, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (467, 'Hardcoded string found')
  - (468, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (471, 'Line exceeds 80 characters')
  - (471, 'Hardcoded string found')
  - (472, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (475, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (483, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (485, 'Line exceeds 80 characters')
  - (485, 'Hardcoded string found')
  - (486, 'Line exceeds 80 characters')
  - (486, 'Hardcoded string found')
  - (487, 'Hardcoded string found')
  - (489, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (497, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (505, 'Hardcoded string found')
  - (506, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
Issues in coin-collector/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
