### ISSUE TITLE
Issue-first try to add auto updater

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/coin-collector#60]
Automated Review Comments
Issues in coin-collector/electron/main.ts:
  - (2, 'Hardcoded string found')
Issues in coin-collector/package-lock.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (135, 'Hardcoded string found')
  - (136, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (150, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Line exceeds 80 characters')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (193, 'Line exceeds 80 characters')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (201, 'Line exceeds 80 characters')
  - (201, 'Hardcoded string found')
  - (202, 'Line exceeds 80 characters')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (210, 'Line exceeds 80 characters')
  - (210, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (219, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (232, 'Line exceeds 80 characters')
  - (232, 'Hardcoded string found')
  - (233, 'Line exceeds 80 characters')
  - (233, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (245, 'Line exceeds 80 characters')
  - (245, 'Hardcoded string found')
  - (246, 'Line exceeds 80 characters')
  - (246, 'Hardcoded string found')
  - (247, 'Line exceeds 80 characters')
  - (247, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (251, 'Line exceeds 80 characters')
  - (251, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (257, 'Line exceeds 80 characters')
  - (257, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (264, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Line exceeds 80 characters')
  - (275, 'Hardcoded string found')
  - (276, 'Line exceeds 80 characters')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Line exceeds 80 characters')
  - (329, 'Hardcoded string found')
  - (330, 'Line exceeds 80 characters')
  - (330, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (338, 'Line exceeds 80 characters')
  - (338, 'Hardcoded string found')
  - (339, 'Line exceeds 80 characters')
  - (339, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Line exceeds 80 characters')
  - (347, 'Hardcoded string found')
  - (348, 'Line exceeds 80 characters')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (365, 'Line exceeds 80 characters')
  - (365, 'Hardcoded string found')
  - (366, 'Line exceeds 80 characters')
  - (366, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (373, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Line exceeds 80 characters')
  - (383, 'Hardcoded string found')
  - (384, 'Line exceeds 80 characters')
  - (384, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Line exceeds 80 characters')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (401, 'Line exceeds 80 characters')
  - (401, 'Hardcoded string found')
  - (402, 'Line exceeds 80 characters')
  - (402, 'Hardcoded string found')
  - (403, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (410, 'Line exceeds 80 characters')
  - (410, 'Hardcoded string found')
  - (411, 'Line exceeds 80 characters')
  - (411, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (422, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (428, 'Line exceeds 80 characters')
  - (428, 'Hardcoded string found')
  - (429, 'Line exceeds 80 characters')
  - (429, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (434, 'Line exceeds 80 characters')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Line exceeds 80 characters')
  - (439, 'Hardcoded string found')
  - (440, 'Line exceeds 80 characters')
  - (440, 'Hardcoded string found')
  - (441, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (448, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (451, 'Line exceeds 80 characters')
  - (451, 'Hardcoded string found')
  - (456, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (462, 'Line exceeds 80 characters')
  - (462, 'Hardcoded string found')
  - (463, 'Line exceeds 80 characters')
  - (463, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (471, 'Line exceeds 80 characters')
  - (471, 'Hardcoded string found')
  - (472, 'Line exceeds 80 characters')
  - (472, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (475, 'Hardcoded string found')
Issues in coin-collector/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
